### PR TITLE
Add Spots to UI/UX

### PR DESCRIPTION
**Pull request by zenangst**
Spots is a view controller framework that makes your setup and future development blazingly fast.

### CODE REVIEW

**Comment by rbarbosa** [comment]
Please Rebase and fix the link.

**Comment by zenangst** [comment]
@rbarbosa should be good now :sunglasses:

**Comment by rbarbosa** [comment]
Thanks!

**Comment by zenangst** [comment]
No, thank you @rbarbosa :sunglasses:

**Pull request merged**
