### PR TITLE
Add DFImageManager

### PR DESCRIPTION
**Pull request by kean**
[DFImageManager](https://github.com/kean/DFImageManager) received a lot of major improvements in recent months and it deserves more :heart:

What makes it better? Basically [everything](https://github.com/kean/DFImageManager#features):

- Uses NSURLSession instead of NSURLConnection which is deprecated in iOS 9
- It's [a pipeline](https://github.com/kean/DFImageManager#design) that can be easily customized and extended (dependency injection is used throughout) which is crucial for non-trivial apps
- Has optional AFNetworking integration via subspec, which allows you to combine the power of both frameworks and not worry about managing two separate networking stacks
- Has optional FLAnimatedImage which is [much better](http://stackoverflow.com/questions/32173846/loading-a-big-gif-with-sdwebimage-caused-ios-app-crash-with-memory-error/32186557#32186557) than SDWebImage implementation
- Better designed API and implementation; core classes have 50% less SLOCs than SDWebImage
- Has nullability annotations and works great with Swift
- Battle-tested, covered with unit tests, has no known issues
- Image decompression and scaling in [a single step](https://github.com/kean/DFImageManager/issues/64)
- Has a lot of advanced features, including advanced [preheating](https://github.com/kean/DFImageManager/wiki/Image-Preheating-Guide), [composite image managers](https://github.com/kean/DFImageManager#composing-image-managers) and more

### CODE REVIEW

**Comment by kean** [comment]
resolved conflicts

**Comment by kean** [comment]
Hey, any reasons you reluctant to adds this? :)

**Comment by RuiAAPeres** [comment]
@kean hey! Let me have a look.

**Comment by RuiAAPeres** [comment]
Add yourself in the Contributors section

**Comment by kean** [comment]
done

**Comment by RuiAAPeres** [comment]
@kean :cake:

**Comment by kean** [comment]
thanks :octocat:

**Pull request merged**
