### PR TITLE
Add Article

### PR DESCRIPTION
**Pull request by piresbruno**
As asked by @RuiAAPeres, here is the pull request

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Add yourself as a contributor.

**Comment by mariusc** [comment]
Hi! Thanks for contributing. Please Add that to the current issue (https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week183.md) instead of creating a new file. Read the [contributing guidelines](https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md) if it's unclear. Or ask here if you have questions :)

**Comment by piresbruno** [comment]
@mariusc is it now according to the guidelines?

**Comment by dkhamsing** [comment]
@piresbruno thanks for the contribution

Please add yourself to the credits

**Comment by tiagoalmeida** [comment]
I have added Bruno to the credits so I can merge the PR 👍 . Thanks.

**Pull request merged**
