### PR TITLE
Update Week72.md

### PR DESCRIPTION
**Pull request by matteogobbi**

### CODE REVIEW

**Comment by rbarbosa** [comment]
The title is misspelled (Anotomy instead of Anatomy)...although the link it
will be more complicated to change, I think the title could be fixed.

**Comment by tiagoalmeida** [comment]
Well spotted rbarbosa. But the title in the issue is coherent with the title in the link :p

**Comment by rbarbosa** [comment]
Yes, I know! But at least, the error would only be seen when landing at
page.

My suggestion is replacing this:
[Anotomy of a TableView(Controller) Architecture](
http://matteogobbi.github.io/blog/2015/03/22/anotomy-of-a-tableview-controller-architecture/
)

with this:
[Anatomy of a TableView(Controller) Architecture](
http://matteogobbi.github.io/blog/2015/03/22/anotomy-of-a-tableview-controller-architecture/
)

But it's only a suggestion.. :)

**Comment by matteogobbi** [comment]
Ops sorry, I go to update and ask for another pull request ;)

Thanks for reporting!

**Comment by matteogobbi** [comment]
Pull Request made.

**Pull request merged**
