### PR TITLE
Add Coordinator vs FlowController

### PR DESCRIPTION
**Pull request by onmyway133**
Hi @mariusc , I don't know if this qualifies enough to be added as an article in this newsletter. But we've used this concept for some times and really like it, so I sum it up a bit. Hope it sheds some light onto the topic of flow controller 😇

### CODE REVIEW

**Comment by rbarbosa** [comment]
Hi @onmyway133. 
I think it fits into the newsletter.
Please fix the author (you) with twitter handler and at the credits remove the @.
Thanks

**Comment by mariusc** [comment]
Hi! I must say it's a pretty unconventional way to write blog articles, but we've also had GitHub gists making it into the newsletter, so this also qualifies :)

**Comment by rbarbosa** [comment]
Thanks!

**Comment by onmyway133** [comment]
@rbarbosa @mariusc Thanks. I 've fixed as you suggested. I've tried many things, Medium, GitHub Pages, but this GitHub Issues encourages me to write much faster 😛

**Pull request merged**
