### PR TITLE
Update Week259.md

### PR DESCRIPTION
**Pull request by velyan**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [x] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by rbarbosa** [comment]
@velyan, can you update your credits to use the github account handler?

**Comment by rbarbosa** [comment]
@velyan ☝️

**Comment by velyan** [comment]
@rbarbosa Updated, thanks

**Comment by rbarbosa** [comment]
Thanks!

**Pull request merged**
