### PR TITLE
Added Scrolling GraphView

### PR DESCRIPTION
**Pull request by nunogoncalves**

### CODE REVIEW

**Comment by mariusc** [comment]
Can you add yourself to the credits, please?

**Comment by nunogoncalves** [comment]
@mariusc 👍

**Comment by RuiAAPeres** [comment]
rebase, there are merge conflicts.

**Comment by tiagoalmeida** [comment]
I am adding this to this week's issue and adding nuno in the credits :). It is easier and faster xD

**Comment by nunogoncalves** [comment]
Totally forgot about this. Sorry about that. :)

**Pull request closed without merging**
