### PR TITLE
Add 'XCode 8: New build settings and improvements'

### PR DESCRIPTION
**Pull request by DarthMike**
A review of analyzer improvements and some new build settings in XCode 8.

### CODE REVIEW

**Comment by rbarbosa** [comment]
Hi @DarthMike, please add yourself to credits.
Thanks!

**Comment by mariusc** [comment]
Thanks for contributing. Two things before we merge this PR:
1. the twitter link doesn't use the correct markdown syntax. It should be [name of link](url_of_link).
2. add yourself to the credits

**Comment by rbarbosa** [comment]
Thank you @mariusc!

**Comment by rbarbosa** [comment]
Btw @DarthMike you might want to fix the word XCode with Xcode in the first paragraph of your article... ;)

**Comment by DarthMike** [comment]
Thanks @rbarbosa fixing all the things now 👍

**Comment by DarthMike** [comment]
Done!

**Comment by dkhamsing** [comment]
thx

**Pull request merged**
