### PR TITLE
Add Hue

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by rbarbosa** [comment]
@zenangst, Week 116 was already published...I hope this doesn't mean you aren't a current subscriber and/or reader. :worried: 
Please move the link to new Week 117 that I added now.
By the way, great tool! :+1:

**Comment by zenangst** [comment]
Oh right, me and my sleepyhead :)

**Comment by zenangst** [comment]
@rbarbosa should be good now I think :sunglasses:

**Comment by rbarbosa** [comment]
Thanks!
:coffee: :cake:

**Pull request merged**
