### PR TITLE
Adding FileBrowser

### PR DESCRIPTION
**Pull request by marmelroy**

### CODE REVIEW

**Comment by rbarbosa** [comment]
@marmelroy, please add yourself to credits.
Thank you.

**Comment by marmelroy** [comment]
Done. Thanks @rbarbosa.

**Comment by rbarbosa** [comment]
Please rebase...sorry.

**Comment by marmelroy** [comment]
Fixed.

**Comment by rbarbosa** [comment]
Great! Thank you.

**Pull request merged**
