### PR TITLE
Add 'match' and ' SwiftyBeaver' (Tools)

### PR DESCRIPTION
**Pull request by p4checo**

### CODE REVIEW

**Comment by p4checo** [comment]
Just noticed 'match' appeared on yesterday's iOS Dev Weekly :sweat:, don't know if it still makes sense to include it in the next goodies.

**Comment by RuiAAPeres** [comment]
It's not because of iOS Dev Weekly, that we wouldn't put it. In this case it's something that happened more than 1 week ago, so let's leave it.

**Comment by RuiAAPeres** [comment]
:cake:

**Comment by p4checo** [comment]
:tada:

**Pull request merged**
