### PR TITLE
Added Pedro's article

### PR DESCRIPTION
**Pull request by mariusc**
Hey,
I read [Pedro's article](http://ppinera.es/2016/11/16/in-a-world.html) this morning and I think it's sad and true. I think it should be included in the edition, maybe even at the top. I'm not a 100% sure how to phrase it, that's why I opened this as a PR instead of adding it directly.

Let me know what you think @tiagoalmeida @RuiAAPeres @rbarbosa @dkhamsing

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
This is a good article. We will add it at the top with a description. Thanks @mariusc.

**Comment by mariusc** [comment]
Great! Feel free to rephrase or rewrite completely what I suggested in this PR :)

**Comment by rbarbosa** [comment]
Great article @mariusc! I agree that it deserves to be on this week edition.

**Comment by tiagoalmeida** [comment]
Seems great! Thanks for the article! Do you have any suggestion for the text at the top?

**Comment by mariusc** [comment]
I added it in this PR https://github.com/iOS-Goodies/iOS-Goodies/blob/8eb87af2c4384feb8ab8096f635830c86d12ee7c/Issues/Week158.md

**Comment by tiagoalmeida** [comment]
Oh, I only clicked in the article :p. Btw, you have an error: highlighting. Kinda vague, but it is hard to describe the problem in a short sentence.

**Comment by mariusc** [comment]
I fixed the typo. Yeah, I agree it's vague, but I don't really know how to phrase it differently without writing an entire paragraph or without making it sound clickbaity or apocalyptical. 
Something like "showing that our iOS community is slowly turning into a pyramidal elitist one" sounds too tough and negative and it's probably not 100% what Pedro meant in his article.
How about something like "... warning not to turn into an elitist community"? I'm not sure. Maybe someone else is a bit more inspired? Worst case scenario, we just link to it without commenting anything: "`<article>`, by `<author>`"

**Comment by dkhamsing** [comment]
Thx Marius

**Comment by tiagoalmeida** [comment]
Yeah, lets see if I get inspired in the meantime xD. Thanks a lot! 👍

**Comment by tiagoalmeida** [comment]
@mariusc What do you think: 

`* [@pepibumur](http://twitter.com/pepibumur)  [asked the question: what if we could flatMap our community ?](http://ppinera.es/2016/11/16/in-a-world.html)`  ?

**Comment by mariusc** [comment]
Hehe; sounds good to me :)

**Pull request merged**
