### PR TITLE
Add implementing tracking with core data

### PR DESCRIPTION
**Pull request by emrepun**
## Checklist

* [X] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [X] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``
* [X] The link is freely available for everyone to read without the need to pay or to create a free account
* [X] I placed the link at the bottom of its category.
* [X] I acknowledge that there's another curation step and that merging this pull request doesn't automatically guarantee the submitted article will be in the newsletter. See [the contributing guides](https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md#contributing)

## Optional

* [ ] Article is not more than 2 weeks old
* [X] Article wasn't submitted before

### CODE REVIEW

**Comment by emrepun** [comment]
I don't use twitter so I added my Github profile at the end of the article as well. 

Moreover, the article is older than two weeks but I still believe it would be beneficial to the community, and it was not published anywhere else before.

**Comment by mariusc** [comment]
Thanks for submitting it; I'll merge this now and we'll see how much new content there will be for this edition. We prefer newer content in general, but we're open to sharing older articles too :)

**Comment by emrepun** [comment]
> Thanks for submitting it; I'll merge this now and we'll see how much new content there will be for this edition. We prefer newer content in general, but we're open to sharing older articles too :)

Sounds good, thank you! :) @mariusc

**Comment by emrepun** [comment]
> Thanks for submitting it; I'll merge this now and we'll see how much new content there will be for this edition. We prefer newer content in general, but we're open to sharing older articles too :)

Hello @mariusc I was wondering if it is the same for sharing tools. I have a framework first released 6-7 months ago and I was wondering if it would be possible to share it with the next newsletter?

**Comment by mariusc** [comment]
Make a PR for the next edition of the newsletter 👍

**Pull request merged**
