### PR TITLE
Added SCXcodeEditorInset and SCXcodeTabSwitcher

### PR DESCRIPTION
**Pull request by stefanceriu**
Here's two brand new Xcode plugins for you :wink: 

SCXcodeEditorInset lets you add an empty (configurable) space to the end of Xcode's editor text view (à la AppCode) and SCXcodeTabSwitcher enables changing Xcode tabs using the ⌘cmd + [1..9] keys.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
rebase please

**Comment by stefanceriu** [comment]
All done.

**Comment by RuiAAPeres** [comment]
:cake:

**Comment by stefanceriu** [comment]
Nice, thank you !

**Pull request merged**
