### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by matteogobbi**

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
Good post, but we created a rule to ensure that our articles are fresh:

"Shouldn't be more than 2 weeks old (although exceptions can be made: e.g. Tools/Libraries).", from our [guidelines](https://github.com/iOS-Goodies/Contributing-Guidelines)

Wasn't this written in the end of 2014?

**Comment by matteogobbi** [comment]
Yes but never published in any newsletter and it has been reviewed last
week. It is interesting and I think could be useful for the community. Up
to you. ;)

On Saturday, 28 February 2015, tiagoalmeida <notifications@github.com>
wrote:

> Good post, but we created a rule to ensure that our articles are fresh:
>
> "Shouldn't be more than 2 weeks old (although exceptions can be made: e.g.
> Tools/Libraries).", from our guidelines
> <https://github.com/iOS-Goodies/Contributing-Guidelines>
>
> Wasn't this written in the end of 2014?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iOS-Goodies/iOS-Goodies/pull/15#issuecomment-76522783>
> .
>


-- 
*Matteo Gobbi*
*Software iOS Engineer *

**Comment by matteogobbi** [comment]
@tiagoalmeida maybe to late? Your colleague already closed. Sorry but I'm more a supporter of what it's useful and still not diffused, rather than what it's new (even if really, this article is pretty new and still just few people is confident with this approach). Bye.

**Comment by RuiAAPeres** [comment]
Hi @matteogobbi this article fails on the 2 week rule. I would bend the rule, if the topic was quite obscure, but nowadays it isn't: it has been covered in a lot of places. The fact of not being published on any newsletter, isn't an argument as well. Independently of that, thank you for your contribution.

**Comment by matteogobbi** [comment]
Hi @RuiAAPeres, it's your newsletter man, i respect your opinion ;)

Anyway, I don't think this approach is diffused. Someone explained what is method swizzling and someone implemented AOP using the same "hack". I arrived to this solution working on a problem I was facing, then I decided to write an article about that. And, I still think that out of frameworks like AOP and so on, this approach is still not diffused. 

Thanks anyway for your reply.

**Pull request closed without merging**
