### PR TITLE
Add More WatchKit Mistakes

### PR DESCRIPTION
**Pull request by dkhamsing**

### CODE REVIEW

**Comment by dkhamsing** [comment]
Updated

**Comment by dkhamsing** [comment]
Hold on..

**Comment by tiagoalmeida** [comment]
@rbarbosa ended up to add those xD, I will close the duplicates.

**Comment by dkhamsing** [comment]
All of em??

**Comment by tiagoalmeida** [comment]
This one at least, going to check the others :)

**Comment by dkhamsing** [comment]
Uhh... didn't see it.

**Comment by dkhamsing** [comment]
Doesn't look like there is any overlap

**Comment by dkhamsing** [comment]
I open another one :confused:

**Pull request closed without merging**
