### PR TITLE
Add RainyRefreshControl

### PR DESCRIPTION
**Pull request by naeemshaikh90**

### CODE REVIEW

**Comment by rbarbosa** [comment]
Hi @naeemshaikh90, thank you for your contribution.
Please fix the link (see: https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md#link-format) and add yourself to credits.

**Comment by naeemshaikh90** [comment]
Mine credit link is already added, but I can't figure out issue with the link. could you help me?

**Comment by rbarbosa** [comment]
Sorry, didn't see you already is in the credits section.
The issue about the link is its author. Since he hasn't a Twitter username it should be use his name.

**Comment by naeemshaikh90** [comment]
Ok thanks I got it!

**Pull request merged**
