### PR TITLE
Add Ohana, a data layer library for fetching and processing contacts.

### PR DESCRIPTION
**Pull request by zethraeus**
Add library: Ohana, a data layer library for fetching and processing contacts. By Uber.

### CODE REVIEW

**Comment by mariusc** [comment]
Can you also add yourself to the credits?

**Comment by zethraeus** [comment]
Is the attribution to @ubereng sufficient?

**Comment by dkhamsing** [comment]
hi, can you add yourself to the credits at the bottom?

**Comment by dkhamsing** [comment]
Week 147 was published, feel free to reopen for Week 148

**Pull request closed without merging**
