### PR TITLE
Adds ImagePicker into the UI/UX section

### PR DESCRIPTION
**Pull request by RamonGilabert**

### CODE REVIEW

**Comment by rbarbosa** [comment]
Please rebase and move the link to section tools.
Thank you.

**Comment by RamonGilabert** [comment]
Should be good now! @rbarbosa sorry about that! :)

**Comment by RuiAAPeres** [comment]
@RamonGilabert the libs looks lovely. :+1:

**Comment by RamonGilabert** [comment]
Oh thank you! :)

**Comment by rbarbosa** [comment]
That's ok!
Thank you.

**Pull request merged**
