### PR TITLE
added some goodies

### PR DESCRIPTION
**Pull request by mariusc**

### CODE REVIEW

**Comment by mariusc** [comment]
not sure if "Minimum viable programmer" is better suited in the "Business" or in "Articles" section. I added it in Business for now. Let me know if I should move it

**Comment by RuiAAPeres** [comment]
@mariusc articles.

**Comment by mariusc** [comment]
@RuiAAPeres moved it

**Comment by rbarbosa** [comment]
FBSimulatorControl was in the previous edition of iOS-Goodies.

**Comment by mariusc** [comment]
oh yeah, you're right. sorry for that

**Comment by rbarbosa** [comment]
No problem!

**Pull request merged**
