### PR TITLE
Adding "How to cache view controllers in iOS" to Week 118

### PR DESCRIPTION
**Pull request by kohola71**
Hi! Thanks for taking this into consideration.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Thanks for the PR!!! Could you please

1. fix the url: (https://medium.com/@gitter/how-to-cache-view-controllers-in-ios-854be6734062)
2. You added an `\n` in the credits, could you please remove it?

**Comment by kohola71** [comment]
Hi! I've introduced the changes as requested. Cheers, Ola.

**Comment by RuiAAPeres** [comment]
@kohola71 thanks  ✨ 

Just one small issue, the **credits** is where you add yourself (kohola71). Is there a reason for you to add [gitterHQ](https://github.com/gitterHQ/gitter)?

**Comment by kohola71** [comment]
It's because I was submitting the article on behalf my colleague @trevorah who is the author, and we both work at Gitter. 

We can add him to the credits instead if you prefer?

**Comment by RuiAAPeres** [comment]
I think you should add yourself. 😊 but if you feel strongly about it, please add your colleague @trevorah

**Comment by kohola71** [comment]
Ok done! I've added myself :) Thanks!

**Comment by RuiAAPeres** [comment]
Super!

**Comment by kohola71** [comment]
hey! for some reason Andy's (trevorah) post has not been published? http://ios-goodies.com/post/139139534906/week-118

**Comment by RuiAAPeres** [comment]
Hi @kohola71 from our [Contribution Guidelines](https://github.com/iOS-Goodies/Contributing-Guidelines):

> If you would like to contribute with a link to the current week's issue send us a Pull Request. After being accepted, the article will stay in the repo, **still it does not guarantee that will be presented on the website, or the newsletter**. This is due to the fact that each section has a limit of 5 articles (in special occasions, we can bend this rule and change the upper limit).

**Pull request merged**
