### PR TITLE
Add article

### PR DESCRIPTION
**Pull request by LisaDziuba**

### CODE REVIEW

**Comment by rbarbosa** [comment]
Hi @LisaDziuba, in the "old times" of iOS-Goodies, we removed any URL shortner or any marketer embebed reference.
Personally, I would continue with this rule, but I'll left to @mariusc the decision to use it or not, since he's the Chef now.

**Comment by LisaDziuba** [comment]
@rbarbosa, thank for the note! I totally understand you. 

We decided to try URL shortner for some our blog articles. As we run a blog on Medium and don't make any popups or "give us your email" stuff, URL shortner is the way to make add campaigns later on (like Facebook adds).  In any case, that a test for us as we didn't try such approach before. If it looks scary or bad, I can just put normal Medium links.

I respect community rules and don't want our articles to get banned because of URL shortner. It's always should be a balance. 

 @mariusc, please let me know what you think.

**Comment by mariusc** [comment]
I agree with Rui. Although I understand why this could be useful for you, I think we should use the full link and not an url shortener

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FranciscoAmado** [comment]
Just my thoughts here..
Doesn't do much difference in the final result.. links in ios-goodies.com are masked with the tumblr redirect and in email with the mailerlite redirect.

**Comment by dkhamsing** [comment]
thank u!

**Pull request merged**
