### PR TITLE
Add article on UI / UX on 110

### PR DESCRIPTION
**Pull request by iOSCowboy**

### CODE REVIEW

**Comment by iOSCowboy** [comment]
Review: @rbarbosa, @tiagoalmeida

**Comment by rbarbosa** [comment]
@iOSCowboy,  this week edition is already out.
I added Week111, so please move the link to this new file.

**Comment by rbarbosa** [comment]
@iOSCowboy please also note the requirements for contributing:
https://github.com/iOS-Goodies/Contributing-Guidelines/blob/master/README.md#requirements

**Comment by iOSCowboy** [comment]
@rbarbosa, article is older than 2 weeks but I think its still relevant and hasn't been shared anywhere else. Does it qualify as an exception?

**Comment by rbarbosa** [comment]
The article has more than one month that is considered old.
Still, I will merge, and we will decide when selecting the articles.

**Pull request closed without merging**
