### PR TITLE
Added simulating signals in Swift, part 1 and part 2

### PR DESCRIPTION
**Pull request by lucianomarisi**

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Could you put it like this:

 Simulating signals in Swift, [part 1](http://www.marisibrothers.com/2016/02/simulating-signals-in-swift-part-1.html) and [part 2](http://www.marisibrothers.com/2016/02/simulating-signals-in-swift-part-2.html) by [@lucianomarisi](https://twitter.com/lucianomarisi)

**Comment by lucianomarisi** [comment]
done :)

**Comment by RuiAAPeres** [comment]
And add yourself to the contributors. 😜

**Comment by lucianomarisi** [comment]
cool, added myself to contributors

**Comment by RuiAAPeres** [comment]
:star:

**Pull request merged**
