### PR TITLE
Added YNAP article

### PR DESCRIPTION
**Pull request by ennioma**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [x] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by mariusc** [comment]
Thanks for submitting this! We featured CascadeKit this week, which also links to the article, so some people might've already seen this. But I'm merging this ayway; just that there's probably a lower chance for it to get in the newsetter next week, depending on what other contributions we'll have.

**Comment by ennioma** [comment]
Oh I didn't see that @pmusolino merged it last week 🤣Sure thanks, feel free to not adding it this week and thanks for having shared CascadeKit!

**Comment by rbarbosa** [comment]
Hey @ennioma nice to "see" you again!
Congrats for the article!

**Comment by ennioma** [comment]
hey ciao @rbarbosa! I hope you are well!

Thanks!

**Pull request merged**
