### PR TITLE
Update Week291.md

### PR DESCRIPTION
**Pull request by mecid**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [x] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by rbarbosa** [comment]
Out of curiosity, why did you put your article in the first place?

**Comment by mecid** [comment]
@rbarbosa just paste it on available space. As I know it doesn’t matter where is it, author generate mail on his own logic.

**Comment by rbarbosa** [comment]
> @rbarbosa just paste it on available space. As I know it doesn’t matter where is it, author generate mail on his own logic.

Ok. But next time, please add it after the last link. Even though you're right about being the curator of the newsletter the responsible to sort the articles, it might sound disrespectful to other contributors like you.
Thanks.

**Comment by mecid** [comment]
@rbarbosa sure, I don't want to disrespect anybody here. Sorry for this situation.

**Pull request merged**
