### PR TITLE
Add Smile

### PR DESCRIPTION
**Pull request by onmyway133**
Give it one more try @mariusc 😉 

Emoji library in Swift.

```
Smile.assemble(emojis: ["👨", "🏫") // 👨‍🏫
Smile.disassemble(emoji: "👨‍🏫") // [👨, 🏫]
Smile.containsEmoji(string: "🎈 and 🎁") // true
```

### CODE REVIEW

**Comment by mariusc** [comment]
@onmyway133 I'm super conflicted by this. In general, we don't accept submitting the same thing twice just because it didn't make it into the newsletter on the first try. In the past, we closed PRs like this. 

However, I just checked and the Contributing guidelines don't specify anything against this (we should probably update them). And last week there was a record number of 11 tools submitted, probably the biggest "competition" in that section ever. So I'm almost tempted to accept a resubmission. But it can't only be my decision. 

@tiagoalmeida @RuiAAPeres @dkhamsing @rbarbosa What do you think?

**Comment by onmyway133** [comment]
@mariusc thanks for your reply. I think I can just close this PR 😢

**Comment by naeemshaikh90** [comment]
@mariusc I think we should give another chance maybe 🤔

**Comment by tiagoalmeida** [comment]
Actually, this was the hardest lib to let go last week. I believe we can give it another try, depending on the tools this week (I will add it myself and @onmyway133 on the credits if that happens). And you are right @mariusc, the guidelines need to be more specific on this subject.

**Comment by onmyway133** [comment]
@mariusc @tiagoalmeida @naeemshaikh90 thanks for giving it another chance. This is going to be like Harvard admission, when people are making more and better libraries. Congrats on the OSS 🎉

**Pull request closed without merging**
