### PR TITLE
Added TextSphere

### PR DESCRIPTION
**Pull request by cagricolak**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [x] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by mariusc** [comment]
Hi! TextSphere was also added to the previous issue on GitHub, and it was merged. However, the library didn't pass our curation and it didn't make it to the newsletter. The general policy is against re-submitting the same link again. Please have a look at the contributing guidelines https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md

**Comment by cagricolak** [comment]
@manuelescrig Hi! TextSphere can't see previous issue on github also iosgoodies website, please check it. last your merge deleted my pod, only have my name is up there. 

https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork

**Comment by mariusc** [comment]
Here's the link to the last GitHub issue: https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week289.md. TextSphere is there and wasn't deleted in the merge. As I wrote before, the library didn't pass our curation and didn't make it to the newsletter.

**Comment by cagricolak** [comment]
ok, but why you are don't delete my name under credits ?

**Comment by rbarbosa** [comment]
Hi @cagricolak.
Your name is under credits because, in fact, you contributed to the newsletter. You were part of the "team" for that issue, regardless if the article was or not included.
Please, don't be offended by that.
To that matter, I, as one of the top most [contributors](https://github.com/iOS-Goodies/iOS-Goodies/graphs/contributors), I have several articles submitted that didn't pass the curation phase.

**Comment by mariusc** [comment]
The credits contain all the people who submitted links to the current issue of the newsletter.

**Pull request closed without merging**
