### PR TITLE
Add 'Leaving the Mac App Store'

### PR DESCRIPTION
**Pull request by andreamazz**
Hi all.  
I'm not sure if the section is appropriate, maybe it can be moved to Business. Anyway I thought this article was pretty important, given the impact that Sketch has.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Business, and add yourself to the credits. Nice article!

**Comment by andreamazz** [comment]
Done :+1:

**Comment by rbarbosa** [comment]
Lol, @andreamazz you might think we are all crazy...
@RuiAAPeres, @andreamazz is already in credits.

**Comment by andreamazz** [comment]
I'm everywhere, I'm your nightmare 😈

**Pull request merged**
