### PR TITLE
added RPaperLayout to markdown

### PR DESCRIPTION
**Pull request by terminatorover**
iOS Goodies, finally made the pull request :)

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
For 3rd party libs, the name is enough (please remove the description)

**Comment by RuiAAPeres** [comment]
This Control was posted on [Week 67](http://ios-goodies.com/post/111504076946/week-67).

**Comment by terminatorover** [comment]
I believe you're referring to RGCardViewLayout, RGPaperLayout is a totally different. But if it's too similar for your liking that's fine.

**Comment by RuiAAPeres** [comment]
You are actually right, read it wrongly. Please just remove the description, keep the name only.

**Comment by terminatorover** [comment]
just did it.

**Comment by RuiAAPeres** [comment]
[RGPaperLayout: Layout that clones the interaction of going through sections when editing your sections in Facebook's paper app](https://github.com/terminatorover/RGPaperLayout),by [@roberageleta](https://twitter.com/roberageleta)

This is considered Name + description.

**Comment by terminatorover** [comment]
Got it.I thought you meant the description for the github repo itself, and that's what i changed.

**Pull request merged**
