### PR TITLE
Added Swift Style Guide article

### PR DESCRIPTION
**Pull request by hkellaway**

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
Sorry for the delay accepting your Pull Request. Could you please rebase ? :scream:

**Comment by hkellaway** [comment]
no prob - all set

**Comment by RuiAAPeres** [comment]
Should be "The Prolific Interactive Swift Style Guid**e**" and not "The Prolific Interactive Swift Style Guid"

**Comment by hkellaway** [comment]
@RuiAAPeres nice catch - fixed

**Comment by RuiAAPeres** [comment]
:heart:

**Pull request merged**
