### PR TITLE
Added Gloss to Week 93 Tools

### PR DESCRIPTION
**Pull request by hkellaway**

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
Can you add yourself to the credits? :)

**Comment by hkellaway** [comment]
will do!

**Comment by hkellaway** [comment]
Rebased

**Comment by tiagoalmeida** [comment]
Sorry, those days were crazy, today I promise I will accept your rebase first :p

**Comment by hkellaway** [comment]
not a problem - rebased again

**Comment by tiagoalmeida** [comment]
Thanks!

**Pull request merged**
