### PR TITLE
Add Hyper Sync

### PR DESCRIPTION
**Pull request by 3lvis**
Sync (1.0.0) eases your every day job of parsing a JSON response and getting it into Core Data. 
It uses a convention over configuration paradigm to facilitate your workflow.

We have two complete examples on how Sync helps to achieve this:

* https://github.com/hyperoslo/Sync/tree/master/Examples/AppNet
* https://github.com/hyperoslo/Sync/tree/master/Examples/DesignerNews

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
The library's name is "Sync".

**Comment by 3lvis** [comment]
@RuiAAPeres Thanks, made the correction.

**Comment by RuiAAPeres** [comment]
@3lvis Could you remove the " — The most simple way of syncing your JSON response into Core Data" to be consistent with the other's libs names.

**Comment by 3lvis** [comment]
@RuiAAPeres done :)

**Comment by RuiAAPeres** [comment]
:heart:

**Pull request merged**
