### PR TITLE
Add business article

### PR DESCRIPTION
**Pull request by LisaDziuba**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [x] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by mariusc** [comment]
Sorry, I'm just preparing to send this week's edition. Let's include that article in the next week's. I'll create the `Week269.md` soon.

**Comment by LisaDziuba** [comment]
@mariusc hey! This article has no relationship to iOS development. But it's the best business piece I read in a long time.

The founder of Gumroad, paying system I'm using, shares his failures as venture-baked company. Very interesting startup journey, showing how venture money can poison. How to fire all the team and manage the product as a single maker. I liked it :)

**Comment by LisaDziuba** [comment]
@mariusc ok!

**Comment by mariusc** [comment]
Can you add it here https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week269.md? Probably easier to close this PR and open a new one. Otherwise, I can add it tomorrow. :)

**Pull request closed without merging**
