### PR TITLE
Add Swiftline

### PR DESCRIPTION
**Pull request by andreamazz**

### CODE REVIEW

**Comment by rbarbosa** [comment]
Please, add yourself to credits.

**Comment by andreamazz** [comment]
I'm already in the credits from a previous PR

**Comment by rbarbosa** [comment]
Sorry, each issue as its own contributors, and each time it's necessary to add it, even if in the past the person already entered that information.

**Comment by andreamazz** [comment]
I'm already in this issue :) #300

**Comment by rbarbosa** [comment]
!!! My bad!!!
Sorry.
:see_no_evil:

**Pull request merged**
