### PR TITLE
Fix link to NightView.

### PR DESCRIPTION
**Pull request by Boris-Em**
My bad, sorry about that, and thanks for the merge!

### CODE REVIEW

**Comment by dkhamsing** [comment]
Oops
Thx!

**Comment by rbarbosa** [comment]
@Boris-Em please fix the tools link with your twitter handler as the author.

**Comment by dkhamsing** [comment]
@Boris-Em uh if you have one! :)

**Comment by rbarbosa** [comment]
Yes he has!
https://twitter.com/Boris_Em

**Comment by dkhamsing** [comment]
@rbarbosa nice work detective

**Pull request merged**
