### PR TITLE
Proposal for article for issue 198.

### PR DESCRIPTION
**Pull request by emenegro**
Hello.

I wrote this article a couple of weeks ago and it is having a little success. I send it because I think it could be interesting for the rest of the community.

Regards!

### CODE REVIEW

**Comment by rbarbosa** [comment]
Thanks @emenegro.
Please change author's link (you) to user twitter handler, and add yourself to credits.
See https://github.com/iOS-Goodies/iOS-Goodies/blob/master/CONTRIBUTING.md

**Comment by rbarbosa** [comment]
The credits should be your GitHub account. See others issues as example:
https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week197.md

**Comment by emenegro** [comment]
Sorry @rbarbosa 😓 I've just updated.

**Comment by rbarbosa** [comment]
@emenegro no problem!
Thanks!

**Pull request merged**
