### PR TITLE
Add Parchment

### PR DESCRIPTION
**Pull request by naeemshaikh90**

### CODE REVIEW

**Comment by mariusc** [comment]
Thanks for all the pull requests! In the future, if you want to add more tools at once, it's ok to add all of them in the same PR. Otherwise, all those PRs et in conflict with each other :)

**Comment by naeemshaikh90** [comment]
Sure, I will keep in mind. and can I have access to direct commit to newsletter?

**Comment by rbarbosa** [comment]
Why do you need direct access?
We are very fast to respond to PR's.

**Comment by naeemshaikh90** [comment]
Yes you guys are very quick to respond to PR's.

**Pull request merged**
