### PR TITLE
Add 'Storing data using CloudKit'

### PR DESCRIPTION
**Pull request by nmarisi**
Added 'Storing data using CloudKit' article.

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
@nmarisi thank you so much! Two things:

1. The full title is: Storing your data on tvOS, part 2: CloudKit
2. Add yourself in the credits!

**Comment by nmarisi** [comment]
Makes sense. Should I resubmit a new pull request then?

**Comment by RuiAAPeres** [comment]
@nmarisi you can just commit again, it will show up here. :star:

**Comment by nmarisi** [comment]
amazing! works like a charm. Thanks a lot for your help Rui.

**Comment by RuiAAPeres** [comment]
Awesome!!! :cookie:

**Pull request merged**
