### PR TITLE
Add article A taste of MVVM and Reactive paradigm

### PR DESCRIPTION
**Pull request by onmyway133**
👋

### CODE REVIEW

**Comment by rbarbosa** [comment]
@onmyway133, @mariusc a few things:
- I don't know why, but @onmyway133 PRs don't seem to appear with the pull request template filled;
- The credits links are always the GitHub account and not twitter;
- I removed the "via Flawless Apps" link. I understand that it can be a paid article, and I'm perfect ok with that and even agree with that, but I'm not ok that iOS Goodies is used as a sponsor like this. This is an open source newsletter where all people can submit whatever they want, and either a company can sponsor the newsletter, or that link as it is in this case is enough to redirect to the company. If it's the case of a sponsor to iOS-Goodies, let me know up front. If it's not, and @mariusc agrees with this, also let me know.

**Comment by onmyway133** [comment]
@rbarbosa Hi, thanks for checking

- "The credits links are always the GitHub account and not twitter"
Sorry, I forgot, I will remember next time
- "I understand that it can be a paid article"
It's not a paid article. I thought it's a convention when the article is written in some publications. I will remember next time.

**Comment by LisaDziuba** [comment]
Sorry, @rbarbosa &  @mariusc, I'm a bit away from the newsletter now and all things here (Techstars program takes all the time).

We're not paying for the articles and do not ask to mention us. In any case, sorry for the inconvenient situation!

**Comment by mariusc** [comment]
Hey all,

Thanks for being more careful than I was when merging :).

Indeed, we have a template both for how the article and credits should look like, and for the PR. This should be the right way to do it. I keep dreaming of making a script/linter that runs on Travis or something similar and checks that the file is in the right format at every PR or push, but time is a limited resource, and I actually have no idea if/when I would implement that.

**Pull request merged**
