### PR TITLE
Add 2 articles

### PR DESCRIPTION
**Pull request by LisaDziuba**

### CODE REVIEW

**Comment by rbarbosa** [comment]
@LisaDziuba I already added the first article. Can you remove it, rebase and update the PR?
Thanks

**Comment by rbarbosa** [comment]
Already fixed! ;)

**Comment by LisaDziuba** [comment]
@rbarbosa thanks!!! sometimes I can be slow)))

**Comment by rbarbosa** [comment]
No worries! :)

**Pull request merged**
