### PR TITLE
Added article to Issue 147

### PR DESCRIPTION
**Pull request by BobDG**

### CODE REVIEW

**Comment by mariusc** [comment]
This was also in Week 146 https://github.com/iOS-Goodies/iOS-Goodies/blob/master/Issues/Week146.md

**Comment by BobDG** [comment]
@mariusc No it wasn't since it was over the limit of 5 :)

**Comment by rbarbosa** [comment]
@BobDG I would say that was a matter of criteria.
Btw the contributing guidelines were updated: https://github.com/iOS-Goodies/iOS-Goodies/pull/538

**Comment by dkhamsing** [comment]
contribution update https://github.com/iOS-Goodies/iOS-Goodies/commit/ce27abced9571517602de73e935b9a803835b9af

**Comment by dkhamsing** [comment]
closing

**Pull request closed without merging**
