### PR TITLE
Add tool link

### PR DESCRIPTION
**Pull request by albertojauregui**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [ ] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by rbarbosa** [comment]
Hi @albertodebortoli, thank you for submission, but this article was already published.

**Comment by albertojauregui** [comment]
Hi @rbarbosa 

You're right, the link was wrong but its fixed now.

What is the correct format for the credits?

**Comment by rbarbosa** [comment]
GitHub account. Look the checklist.

Don't forget to rebase.

**Comment by rbarbosa** [comment]
The PR has conflicts. Please rebase.

**Comment by albertojauregui** [comment]
Done!

**Comment by rbarbosa** [comment]
Nope.

**Comment by albertojauregui** [comment]
Sorry I don't know how to make a rebase, let me find how to do that.

**Comment by rbarbosa** [comment]
I can do that.

**Comment by albertojauregui** [comment]
Thank you @rbarbosa

**Pull request merged**
