### PR TITLE
Add Cache

### PR DESCRIPTION
**Pull request by onmyway133**
Hi, I hope you like this as I do. Here is [Cache](https://github.com/hyperoslo/Cache), it was updated to Swift 4 with strong support for `Codable`. In fact, it relies on `Codable` and `JSONEncoder` to do its job, so user mostly get persistency out of the box.

Some features

- Memory and disk cache
- Thread safe
- Sync and async APIs
- Saving primitive object like `Int`, `Float`, ...
- Saving `Data`, `Codable` and `UI|NSImage`
- Expiry and clearing of expired objects
- Serialising json string, data, dictionary to `Codable` object
- Fine grain control with `MemoryConfig` and `DiskConfig`

### CODE REVIEW

**Comment by mariusc** [comment]
I'm a bit unsure about this one, we had Cache featured in Issue 125. I understand it's been updated to Swift 4 and with some new features, but I'm not sure if that means we should include it again

**Comment by onmyway133** [comment]
@mariusc Ah sorry I missed that. But this is mostly completely new stuff in an old name.

**Comment by mariusc** [comment]
I'll merge the PR for now, and think about it some more when making the newsletter

**Comment by onmyway133** [comment]
@mariusc you're the best ❤️

**Pull request merged**
