### PR TITLE
Add TypedTextAttributes

### PR DESCRIPTION
**Pull request by muukii**
## Checklist

* [ ] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [ ] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github]``

## Optional

* [ ] Article is not more than 2 weeks old
* [ ] Article wasn't submitted before

### CODE REVIEW

**Comment by mariusc** [comment]
Can you add yourself to the credits?

**Comment by muukii** [comment]
@mariusc Okay! I will

**Comment by muukii** [comment]
@mariusc 
I added.
Is it okay?

**Comment by rbarbosa** [comment]
Thanks!

**Pull request merged**
