### PR TITLE
added rxswift article

### PR DESCRIPTION
**Pull request by icanzilb**
http://rx-marin.com/post/rxswift-timer-sequence-manual-dispose-bag/

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
Hi @icanzilb could you remove this one:

```
+* [Manually disposing a bag and creating a timer with RxSwift](http://rx-marin.com/post/rxswift-timer-sequence-manual-dispose-bag/) by [@icanzilb](https://twitter.com/icanzilb)
```

Since it's from almost one month ago. ❤️

**Comment by icanzilb** [comment]
It was not promoted anywhere but as you wish :)

**Comment by RuiAAPeres** [comment]
@icanzilb from the guidelines:

> Shouldn't be more than 2 weeks old (although exceptions can be made: e.g. Tools/Libraries).

If you didn't had a more recent article, I would be ok with it. But your latest one, IMO, seems more interesting.

**Comment by icanzilb** [comment]
fair enough

**Comment by RuiAAPeres** [comment]
🍰

**Pull request merged**
