### PR TITLE
Add UX & UI article

### PR DESCRIPTION
**Pull request by LisaDziuba**
I hate dropdown forms, but some UX ideas in this post make sense.

### CODE REVIEW

**Comment by dkhamsing** [comment]
@tiagoalmeida ^^

**Comment by LisaDziuba** [comment]
Now I can go sleep. My contribution plan for today is completed 😅

**Comment by tiagoalmeida** [comment]
Fair enough! Thanks 👍

**Comment by tiagoalmeida** [comment]
(Accepted in this week to be fast, but I will move it to week 188 tomorrow, also I am in a hurry 😅)

**Pull request merged**
