### PR TITLE
Add BubbleTransition and 'iOS9 Notifications and Text Input'

### PR DESCRIPTION
**Pull request by andreamazz**
:+1:

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
rebase please :)

**Comment by andreamazz** [comment]
Done :smiley:

**Comment by RuiAAPeres** [comment]
Still not rebased @andreamazz

**Comment by andreamazz** [comment]
Sorry about that, long day :sweat_smile:  
Should be fine now

**Pull request merged**
