### PR TITLE
Update

### PR DESCRIPTION
**Pull request by dkhamsing**
- Pinpoint
- Google APIs
- Spark
- Building an App from Start to Finish	 
-	 Build Stability

### CODE REVIEW

**Comment by dkhamsing** [comment]
Merge ready :grin:

**Comment by RuiAAPeres** [comment]
:cake:

**Comment by dkhamsing** [comment]
Merci

**Comment by rbarbosa** [comment]
Hum...Monads in Swift was in Articles section...

**Comment by dkhamsing** [comment]
Ooops. Let me send an update sorrys

**Pull request merged**
