### PR TITLE
Add few links

### PR DESCRIPTION
**Pull request by rbarbosa**
Articles:
 - Caesar cipher in Swift;
 - Putting Mobile Back End As A Service Into Practice (Part 2);
 - Building an Instagram-Like App with Parse and Swift

Business:
 - 3 Things Every Indie Business Owner Should Know

UI/UX:
 - Imagining Basecamp on Apple Watch;
 - The UX of the Future- The future kind of has a UI;
 - 6 Wearable Design Principles — 2015

Videos:
 - Prototyping and Design with Lyft & Pixate

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
Here comes the pack again :rocket: 

You need to rebase @rbarbosa :(

**Comment by RuiAAPeres** [comment]
And yet another rebase.

**Comment by rbarbosa** [comment]
I think it's already done.

**Comment by RuiAAPeres** [comment]
@rbarbosa  It's not, can't merge.

**Pull request merged**
