### PR TITLE
SpeedLog article and Tool

### PR DESCRIPTION
**Pull request by kostiakoval**
Submitting my tool :)
The link to article is not working (it's waiting for approval in the medium)

It's my Sunday routine - Submit a RP to iOS-Goodies :)

### CODE REVIEW

**Comment by RuiAAPeres** [comment]
@kostiakoval would you mind the credits Section and add your name to it?

**Comment by kostiakoval** [comment]
Like that? 
I haven't seen the Credits section in previous iOS-Goodies weeks.md

**Comment by RuiAAPeres** [comment]
@kostiakoval like we have on the website: http://ios-goodies.com/post/123667287506/week-87

**Comment by kostiakoval** [comment]
@RuiAAPeres  Done! Sorry that it took so long time! Probably I need to move to  my own website

**Comment by RuiAAPeres** [comment]
@kostiakoval still not according to the format. :(

**Comment by kostiakoval** [comment]
@RuiAAPeres ups 😊,  is it ok now?

**Comment by RuiAAPeres** [comment]
Nice!

**Comment by kostiakoval** [comment]
Thanks!

Every time do PR to iOS-Goodies I remembering your first comment to my PR. 
remember it? :D
Giphy

**Pull request merged**
