### PR TITLE
Add joke about Engineering Estimations

### PR DESCRIPTION
**Pull request by LisaDziuba**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

This is just hilarious and I'm sure you have seen this 😂 Maybe it will suit somewhere?

### CODE REVIEW

**Comment by mariusc** [comment]
Hey Lisa! Thanks for adding that. I'm not sure yet where it fits; I don't think it should be in the Business section. Maybe some kind of "And finally", like Dave does for iOS Dev Weekly? But I wouldn't introduce a new category just for this. I'll move this to the top of the file and try to figure out where it's best to include it. But there's also a chance it won't make it to the final issue, depending on how I can integrate it :)

**Comment by rbarbosa** [comment]
My 2 cents. Either include it on your introduction or just don't include it. :)

**Comment by mariusc** [comment]
Yeah, I think that's what I'll do; let's see how it fits in the introduction :) (as soon as I have an introduction for this week 😅)

**Comment by LisaDziuba** [comment]
I'm feeling that I'm submitting uncertainty to iOSGoodies 😂

**Pull request merged**
