### PR TITLE
added link to settings deeplinking article

### PR DESCRIPTION
**Pull request by mariusc**

### CODE REVIEW

**Comment by tiagoalmeida** [comment]
Rebase please :)

**Comment by mariusc** [comment]
I'm not a git expert, so I hope I got this right :). Is it ok now?

**Comment by tiagoalmeida** [comment]
Just need you to add yourself to the credits and then it is perfect :D

**Comment by mariusc** [comment]
Done. 

Minor mention: it's the first time I see the Contributors section written by the contributors in an iOS-Goodies issue. Can we have some guidelines on that (update these https://github.com/iOS-Goodies/Contributing-Guidelines)? 

I can make a pull request later for that, if I first get this clarified with you. I see the contributors have a name and a link: can the name be full name or must it be the github username? Also, the url, can it point to the contributor's twitter profile, or website, etc, or must it be the github profile of the contributor?

**Comment by RuiAAPeres** [comment]
@mariusc you are 100% right. It's something we decided to do for this issue, since we were forgetting to add the Credits to the issues. We will fix this. Thanks for your feedback. 👍

**Pull request merged**
