### PR TITLE
Chess Tactics & Lessons

### PR DESCRIPTION
**Pull request by plivesey**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Other stuff

So, I'm not 100% sure if you even support the indie apps section any more. It seems like you do from the contributing guidelines, but it's not in the default template.

If you don't want to add indie apps, or don't think my app is a good fit for the newsletter, please feel free to deny my pull request. I wasn't sure if this was appropriate, but decided I may as well submit it 😄 .

About me/my app:
The app is a chess training app which is great for experts and beginners (just added the beginner onboarding a couple of months ago and I think you actually included the article I wrote about that experience in the newsletter). It includes puzzles, lessons and opening training - everything you need to improve except actually playing chess against other people. It's community based, so all the content is crowd sourced!

It's not a new app (potentially this also disqualified me...). I've been working on the app on off for a few years, but recently, it's become my sole source of income (and that's not much income, lol). My wife and I are trying to up our marketing game as we're not getting too many downloads. (p.s. if you have any experience marketing indie apps, we'd love any advice you have!)

Anyway, let me know if you have any questions and if this is an appropriate PR.

Thanks either way for all your awesome work!

### CODE REVIEW

**Comment by mariusc** [comment]
Thanks for suggesting this. Indeed, since a long long time ago, the contributing guidlines say we support indie apps. Since I started taking care of iOS Goodies last year, we haven't linked to any indie app. And to be honest, I don't remember ever seeing an indie app promoted in iOS Goodies (I'll search in the archives later, to be sure).

While I'd really like to support indie apps by promoting them, I find it very hard to draw a line to what should and shouldn't go in the newsletter. For example, there are big/famous indie apps, like PCalc, for example, which I'm assuming is quite profitable. There are other indie apps, like SnapThread, which already have a lot of exposure from being featured in MacStories or other publishings. And there are probably a lot of new developers, who just made their first app, and who would want to get the word out about it. I'm afraid it will be very hard to draw a line here as regards to what goes in the newsletter and what doesn't.

I'll give this a bit more thought and come back with an answer

**Comment by plivesey** [comment]
You guys are doing something awesome here and have always supported me with promoting my blog posts. I really don’t want to abuse this platform for something it’s not intended for so it’s totally ok if you would prefer to leave this out. We’re just throwing darts in terms of marketing so trying everything :D.

**Comment by plivesey** [comment]
Looks like you decided against including this one, so going to close this.

Thanks again. I'll have some more content for you soon 😉

**Comment by mariusc** [comment]
Hi! Yes, sorry for that. Promoting indie apps is something I would like to do, but I need to figure out a good way of deciding which apps are suited for this and which aren't. Until I do that, I have removed the indie apps section form the contributing guidelines. I've written above some of my concerns about this. I'm sorry for the inconvenience.

**Comment by plivesey** [comment]
No inconvenience at all. And sounds like a good plan to me.

:D

**Pull request closed without merging**
