### PR TITLE
Got suggestion to add my lib from awesome-ios

### PR DESCRIPTION
**Pull request by younatics**
Make Pull request! :)

### CODE REVIEW

**Comment by naeemshaikh90** [comment]
Hey @younatics thanks for contributing to `iOS Goodies` 🍰
It should be added in **Tools/Controls** section. and add yourself in credits.

**Comment by younatics** [comment]
I will do it again

**Comment by naeemshaikh90** [comment]
Hey @younatics you also can edit this PR to make changes and one more thing title of the PR should be relevant and descriptive,  such that it would be easy to review PR.

Thanks for your contribution.😀

i.e. 'Add YNExpandableCell to Tools/Control'

#744

**Comment by naeemshaikh90** [comment]
Pull requests should be referenced like this such that it would be easier for collaborator to manage PR.

i.e. '#744'

**Pull request closed without merging**
