### PR TITLE
Add Article

### PR DESCRIPTION
**Pull request by LisaDziuba**
Error handling with Swift on the server.

### CODE REVIEW

**Comment by dkhamsing** [comment]
thx

**Comment by LisaDziuba** [comment]
@dkhamsing do I still have time to submit more articles to this issue?
I have some good one, but need to find it in my bookmarks :)

**Comment by dkhamsing** [comment]
looks like no https://github.com/iOS-Goodies/iOS-Goodies/commit/1ea1aad4e4d62443d825660ea4361b6b1248905f

please wait until tomorrow :)

**Comment by LisaDziuba** [comment]
omg 😂
How can I survive until tomorrow?

**Comment by tiagoalmeida** [comment]
ahah. I was about to send the email, please submit it and I might edit it online! Just in time!

**Pull request merged**
