### PR TITLE
Add UX & UI article

### PR DESCRIPTION
**Pull request by LisaDziuba**
## Checklist

* [x] The links are in the correct format: ``[Title of the Article](link), by [@author/`s Twitter username](link-for-twitter)``
* [x] I added my self to the credits with my GitHub account: ``[GitHub account](link-to-github)``

## Optional

* [ ] Article is not more than 2 weeks old
* [x] Article wasn't submitted before

### CODE REVIEW

**Comment by LisaDziuba** [comment]
that's not a new article but it's cool

**Comment by rbarbosa** [comment]
Yep, the article is too old. I'll let @mariusc decide.

**Comment by mariusc** [comment]
Sorry, I think we should stick to newer articles :)

**Comment by LisaDziuba** [comment]
sure
no worries!

**Pull request closed without merging**
